Develop
OMatiykiv/Flexbox_grid pull request #1
Opened 2019-11-08 14:21 UTC by OMatiykiv

2019-11-11 11:53 UTC, karmeljuk requested changes
great job. Minor changes needed

2019-11-11 11:53 UTC, karmeljuk commented on css/styles.css
> +  margin: 1vmin 0.5vmin;
.5vmin

2019-11-11 11:53 UTC, karmeljuk commented on css/styles.css
> +  margin: 1vmin 0.5vmin;
.5vmin

2019-11-11 20:32 UTC, OMatiykiv commented on css/styles.css
> +  margin: 1vmin 0.5vmin;
done

2019-11-11 20:32 UTC, OMatiykiv commented on css/styles.css
> +  margin: 1vmin 0.5vmin;
done

2019-11-12 09:02 UTC, karmeljuk approved these changes

2019-11-12 09:02 UTC, merged